In [1]:
import numpy as np

In [2]:
x = [3,4]

In [3]:
x = np.array(x)

In [4]:
x

array([3, 4])

In [5]:
y = np.expand_dims(x, 0)
y

array([[3, 4]])

In [6]:
pred = y *2
pred

array([[6, 8]])

In [7]:
l = [3,4]
a = l*2
a

[3, 4, 3, 4]